version: '1.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Restore
  - cmd: dotnet restore
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
artifacts:
    - path: '**\*.nupkg' # find all NuGet packages recursively
deploy:
  provider: NuGet
  api_key:
    secure: S1vZmjBAtK+cgiJL1R6dN7fhlf+CqcNEM/JfZ7meE/LzGQssadsflsPpog/TTb3H
  skip_symbols: true  
